---
name: "Lint PR Title"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v2.2.1
        with:
          success-state: Title follows conventional commits
          failure-state: Title does not follow conventional commits
          context-name: convention-pr-title
          preset: conventional-changelog-angular@latest
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}